### PR TITLE
Only output necessary Stackage dependencies

### LINKED ISSUE #19: Prune packages.nix
It is not necessary for packages.nix to list every single package in the LTS: only the packages that are dependencies or transitive dependencies of the projects in the given stack.yaml can be listed. This pruning can be pretty simple and does not have to be perfect: we can just use the argument sets as the set of dependencies even if some would be unused due to any flags in the expression itself.

This should allow a much nicer time when we check in packages.nix into code repository and more importantly, a much more meaningful diff when dependency set is updated: it will become clear what packages we added, updated or removed.

### PR DESCRIPTION
**Pull request by Fuuzetsu**
Closes #19.

### CODE REVIEW

**Comment by Fuuzetsu** [comment]
Notes:

1. I didn't profile it but it shouldn't be _too_ awful.
2. It may possibly be significantly less code to use the graph API present.
3. Perhaps it should live outside of `Runner.hs`.

**Comment by 4e6** [comment]
Thanks for investing your time into this feature. 

I apologize for taking so much time to respond. I took some time to test this version. It works very well, but and found one unexpected behavior.

## Info

Some packages have `libraryToolDepends` attribute, for example, haskell-src-exts depends on happy:

```
  "haskell-src-exts" = callPackage
    ({ mkDerivation, array, base, containers, cpphs, directory
     , filepath, ghc-prim, happy, mtl, pretty, pretty-show, smallcheck
     , tasty, tasty-golden, tasty-smallcheck
     }:
     mkDerivation {
       pname = "haskell-src-exts";
       version = "1.18.2";
       sha256 = "0hq9f6r67gkhad4cc4dhahrwrz9kxfibhk8qrw5j0p7cvh23hn1i";
       libraryHaskellDepends = [ array base cpphs ghc-prim pretty ];
       libraryToolDepends = [ happy ];
       testHaskellDepends = [
         base containers directory filepath mtl pretty-show smallcheck tasty
         tasty-golden tasty-smallcheck
       ];
       doHaddock = false;
       doCheck = false;
       homepage = "https://github.com/haskell-suite/haskell-src-exts";
       description = "Manipulating Haskell source: abstract syntax, lexer, parser, and pretty-printer";
       license = stdenv.lib.licenses.bsd3;
     }) {};
```

So, when derivation have `happy` dependency, I expect to see happy in `packages.nix` Stackage LTS.

## Issue

I was able to create a setup where it is not, the case. Consider the project consisting of two following files:

stack.yaml:
```
resolver: lts-9.1
extra-deps:
- haskell-src-meta-0.6.0.14
# haskell-src-exts-1.17.1 is a dependency of haskell-src-meta
```

closure-test.cabal:
```
name:                closure-test
version:             0.1.0.0

library
  default-language:    Haskell2010
```

Running `stackage2nix` in this directory I expect to see `happy` in `packages.nix`, but it is not generated.

## Not an issue

Interesting enough that issue is not reproduced when haskell-src-exts is a direct dependency in stack.yaml:

```
resolver: lts-9.1
extra-deps:
- haskell-src-exts-1.17.1
```

Running `stakckage2nix` with this stack.yaml, package `happy` is successfully added to `packages.nix` set.

Can you please take look at this issue? It is not very severe, but still, it would be cool to generate Nix Stackage LTS as close as possible to the original.

**Comment by Fuuzetsu** [comment]
Hi,

That's a good catch and valid point. I agree `happy` should be in `packages.nix`: indeed I just verified in the project I'm about to put `packages.nix` into and we have 4 packages there that depend on `happy` yet `happy` is not coming from `packages.nix`. I'll look into this after work today (~4h+).

**Comment by Fuuzetsu** [comment]
It seems that `testHaskellDepends` also suffers from the same fate: `QuickCheck` is not listed in `packages.nix` even though it should be. This is a bit more serious problem as it's a library and version bounds matter a bit more here than on rarely-changing binary happy.

**Comment by Fuuzetsu** [comment]
I looked into this a little. The problem is that stackage does _not_ specify any tools needed to build the package.

Notably `  Build-Tools:          happy >= 1.19` gets ignored`. Build tools section in Haskell world has always been a point of disputed but as far as I understand, it's pretty much ignored by cabal and stack for dependency resolution.

I believe there is _some_ hack somewhere which might install these for you during build but I think they don't get included as part of build plan.

So what happens is that `happy` is _not_ a dependency according to stackage therefore we don't include it in `packages.nix`. However we subsequently run cabal2nix on the cabal file and cabal2nix _does_ look at `build-tools` because it's using carefully curated nixpkgs which can satisfy the tool needs.

There are a few ways forward but all seems awful. The most sane one I think is:

* generate derivation for every package in stackage regardless of what we think dependencies may be
* traverse every `reachable` package's derivation and recursively pull out `haskell` and `tool` dependencies: similar to what's done in commit above but we now work over cabal2nix-generated derivations rather than stackage build plan
* only keep derivations from the set generated above

this way we should have minimum reachable set including tools

I'll try to implement it now.

**Comment by Fuuzetsu** [comment]
Please have another look, I think you'll be quite pleased. I have reverted and squashed away nearly all changes made initially as they were no longer needed. I have left `reachable` as a `Set` however as to not induce a quadratic time lookup.

**Comment by 4e6** [comment]
All good, thanks! You are right; internals definitely requires some refactoring. I hope to organize everything eventually.

**Comment by Fuuzetsu** [comment]
One thing to note here is that it's possible to easily speed up the implementation used here by building the node set iteratively by following Node dependencies from set of reachable Nodes and only generate Derivation for each of these afterwards. This way we only generate derivations we need and we have only reachable dependencies by construction: win-win. This is mostly a self reminder to do that in spare few minutes.

**Pull request merged**
